name: test

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.*'

      - name: checkout repo
        uses: actions/checkout@v3

      - name: go test
        run: go test -v .
